### PR TITLE
build: add .github/CODEOWNERS

### PR DESCRIPTION
**Pull request by dougsland**
Automatically add owners to review new PRs.

### CODE REVIEW

**Comment by dougsland** [comment]
After this change, no need to mention people in the PR for review. @rhatdan @lsm5

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
@dougsland add your own id as well.

**Comment by dougsland** [comment]
> @dougsland add your own id as well.

Ok, I will add. Thanks!

**Pull request merged**
