### PR TITLE
qm.container: add MemoryMax and MemoryHigh

### PR DESCRIPTION
**Pull request by dougsland**
Add new settings for [Service]

See-Also: https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/merge_requests/102

### CODE REVIEW

**Comment by dougsland** [comment]
@alexlarsson

**Comment by dougsland** [comment]
> I'm not sure why we need this? It changes nothing?

Nothing but I am curious about why you guys added here: https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/merge_requests/102

**Comment by alexlarsson** [comment]
The defaults there change nothing, but a manifest for a car can define `qm_memory_max=4G`, and then it is very useful. I don't think there are any useful values we can hardcode in qm itself though, as we know nothing about the end-user system capacity and expected load.

**Comment by dougsland** [comment]
> The defaults there change nothing, but a manifest for a car can define `qm_memory_max=4G`, and then it is very useful. I > don't think there are any useful values we can hardcode in qm itself though, as we know nothing about the end-user
> system capacity and expected load.

However, it's very useful to all users have a single template from the main qm repo. Today we have auto case but tomorrow we will have more cases for sure. Based on that, I don't think we need a new release but def. merge this one. Sounds good to you too @alexlarsson ?

**Comment by alexlarsson** [comment]
I'm not sure what you mean. All this PR is doing is set a few options to their default values. It will change nothing in the behavior. Do you mean that having this in the qm.container file is a kind of documentation for these?

**Comment by dougsland** [comment]
> I'm not sure what you mean. All this PR is doing is set a few options to their default values. It will change nothing in the
> behavior. Do you mean that having this in the qm.container file is a kind of documentation for these?

Yes

**Comment by alexlarsson** [comment]
Sure, that sounds fine then.

**Pull request merged**
