### PR TITLE
Build selinux on platforms without user_namespace class

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by lsm5** [comment]
@rhatdan could you please also remove the user_namespace sed line from `rpm/qm.spec` ? That'll verify if the change works well with the rpm.

**Comment by lsm5** [comment]
> @rhatdan could you please also remove the user_namespace sed line from `rpm/qm.spec` ? That'll verify if the change works well with the rpm.

along with `no_user_namespace` conditionals at lines 15-21 in the spec.

**Comment by dougsland** [comment]
removing the sed in the spec +1. Otherwise, the makefile solution is great solution.

**Comment by dougsland** [comment]
Otherwise, we can merge now and later remove in a single commit the sed from spec @lsm5

**Comment by dougsland** [comment]
Solves: https://github.com/containers/qm/pull/47

**Comment by lsm5** [comment]
> Otherwise, we can merge now and later remove in a single commit the sed from spec @lsm5

either way works. But, I hope the spec file change verification lands before we cut a new release. Might be just a nit but better to have that change in when we have the chance.

**Review by lsm5 — APPROVED** [review]
LGTM once build passes and PR rebased on main.

**Comment by lsm5** [comment]
copr builds seem to have failed because of merge conflicts. So, I think rebasing on main will take care of that too.

**Pull request merged**
