### PR TITLE
 Adding Dennis as default reviewer

### PR DESCRIPTION
**Pull request by Yarboa**

### CODE REVIEW

**Comment by Yarboa** [comment]
@dougsland there is an error that users does'nt have write permission to qm repo,
Do they need to be members of containers project?

**Comment by dougsland** [comment]
> @dougsland there is an error that users does'nt have write permission to qm repo, Do they need to be members of containers project?

yes, I can fix that.

**Comment by dougsland** [comment]
> > @dougsland there is an error that users does'nt have write permission to qm repo, Do they need to be members of containers project?
> 
> yes, I can fix that.

sent invite to both, they need to accept.

**Comment by dougsland** [comment]
LGTM

@lsm5 @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Welcome  @dennisbrendel @priyverm

**Pull request merged**
