### PR TITLE
Additional SELinux rules found in testing

### PR DESCRIPTION
**Pull request by rhatdan**
Bump to v0.4.2

### CODE REVIEW

**Comment by dougsland** [comment]
LGTM

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
> let's try to get @dougsland 's e2e tests in packit or github actions before we cut the next minor release.

@yarboa would you be interested in this?

**Comment by Yarboa** [comment]
Yep, Currently i can not complete deployment e2e with success
Trying to understand the RCA

**Pull request merged**
