### PR TITLE
qm.if: add remaining wayland rules

### PR DESCRIPTION
**Pull request by aesteve-rh**
Add remaining rules required to support
booting and running the wayland scenario,
with a compositor, session creation,
qm dbus management, and all required pieces.

Note that running pem_selinux for creating
the session will be blocked, as it falls back
to unconfined_u with the current rules.

### CODE REVIEW

**Review by Yarboa — APPROVED** [review]
LGTM
Please suggest test scenario for testing

**Comment by aesteve-rh** [comment]
> Please suggest test scenario for testing

I do not mind doing so, but this is a far more complex scenario than the QM-ASIL IPC. So detailing and replicating everything that is needed is going to be a big effort. I'd suggest taking a look at the scenario we developed in [autosd-demo](https://gitlab.com/roberto-majadas/autosd-demo/-/merge_requests/65). The CLI comes with an `export` subcommand to obtain a fully aib-compatible project, with all extra files and proper osbuild-manifest. That should speed up things.

**Comment by aesteve-rh** [comment]
cc @telemaco

**Comment by Yarboa** [comment]
> > Please suggest test scenario for testing
> 
Please create an issue even for autosd demo
We can discuss that later on in the issue, thanks

**Pull request merged**
