### PR TITLE
make .packit.sh pass shellcheck

### PR DESCRIPTION
**Pull request by sandrobonazzola**
make .packit.sh pass shellcheck

### CODE REVIEW

**Comment by dougsland** [comment]
LGTM

**Comment by lsm5** [comment]
@dougsland @sandrobonazzola btw, would either of you be ok with being the main admin on the `qm` fedora rpm? I'm currently the main admin, but I'm not so active on qm anymore. If you're gonna be active, I can hand it off to you.

**Comment by dougsland** [comment]
> @dougsland @sandrobonazzola btw, would either of you be ok with being the main admin on the `qm` fedora
> rpm? I'm currently the main admin, but I'm not so active on qm anymore. If you're gonna be active, I can hand it
> off to you.

Just a question, isn't automatically job build/publish?

**Comment by sandrobonazzola** [comment]
> @dougsland @sandrobonazzola btw, would either of you be ok with being the main admin on the `qm` fedora rpm? I'm currently the main admin, but I'm not so active on qm anymore. If you're gonna be active, I can hand it off to you.

I'm not really that much involved with `qm` I'm just trying to use it :-) But I can help with the fedora packaging maintenance.

**Comment by lsm5** [comment]
> > @dougsland @sandrobonazzola btw, would either of you be ok with being the main admin on the `qm` fedora
> > rpm? I'm currently the main admin, but I'm not so active on qm anymore. If you're gonna be active, I can hand it
> > off to you.
> 
> Just a question, isn't automatically job build/publish?

Packit will create PRs to dist-git on every upstream release, but those have to be merged by a human. Also, there might be bugs coming in, and I'd prefer if the default assignee be someone who is very active on it.

**Pull request merged**
