### PR TITLE
Default timezone to local to match the hosts

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/qm/issues/113

### CODE REVIEW

**Comment by dougsland** [comment]
LGTM

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Review by Yarboa — APPROVED** [review]
LGTM, but we have an Issue hirte pylib

**Comment by sandrobonazzola** [comment]
> LGTM, but we have an Issue hirte pylib

Can you please add more details?

**Comment by Yarboa** [comment]
> > LGTM, but we have an Issue hirte pylib
> 
> Can you please add more details?

@rhatdan Please review/approve #119 and rebase and merge :)

**Comment by dougsland** [comment]
> > > LGTM, but we have an Issue hirte pylib
> > 
> > 
> > Can you please add more details?
> 
> @rhatdan Please review/approve #119 and rebase and merge :)

Just approved and merged, thanks @Yarboa. @rhatdan  is more busy this week than normal, probably he will see this comment little late. Merged!

**Pull request merged**
