### PR TITLE
e2e: add markdown-cli linter

### PR DESCRIPTION
**Pull request by dougsland**
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

### CODE REVIEW

**Review by sandrobonazzola — COMMENTED** [review]
Is there any reason for running linting on the code during end to end tests?
I assume this should be covered by pre-commit already

**Comment by dougsland** [comment]
> Is there any reason for running linting on the code during end to end tests?
> I assume this should be covered by pre-commit already

@sandrobonazzola 
bluechi project uses this markdown lint. Would be nice to have the same one they run there too.

https://github.com/containers/bluechi/blob/main/.github/workflows/lint.yml#L101

**Comment by sandrobonazzola** [comment]
I won't be the one blocking this PR but IMHO if this container is going to be used for development it should live in another place, not in e2e. Having a bigger container for e2e testing means we consume more bandwidth, storage and time to run e2e testing. This consumes power and money, we should minimize the e2e test environment, not making it bigger.

**Comment by dougsland** [comment]
> I won't be the one blocking this PR but IMHO if this container is going to be used for
> development it should live in another place, not in e2e. Having a bigger container for e2e
> testing means we consume more bandwidth, storage and time to run e2e testing. This 
>consumes power and money, we should minimize the e2e test environment, not making it
> bigger.

Thanks Sandro! We can always improve the solution. Let's merge now, I am aware that @Yarboa is working in some improvements regarding layers/images etc. Also, fell free to create an issue in the repo with the details and improvements you visualize so we can address it.

**Pull request merged**
