### PR TITLE
RPM: set AllowedCPUs in quadlet file post install

### PR DESCRIPTION
**Pull request by lsm5**
Fixes: #24

### CODE REVIEW

**Comment by lsm5** [comment]
let me try out the packit rpms on a gce instance.

**Comment by lsm5** [comment]
works well on c9s on GCE with nproc=2

@rhatdan PTAL

**Comment by lsm5** [comment]
err wait...

**Comment by lsm5** [comment]
I guess this is good to go. qm.service is still failing on `/dev/kvm` not found, but that should be fixed once https://github.com/containers/podman/pull/18378 is merged and built on copr.

**Comment by lsm5** [comment]
@rhatdan PTAL, ready now

> I guess this is good to go. qm.service is still failing on `/dev/kvm` not found, but that should be fixed once [containers/podman#18378](https://github.com/containers/podman/pull/18378) is merged and built on copr.

The podman PR cherry-pick will merge anytime now and will soon be available on `rhcontainerbot/qm` copr.

**Comment by rhatdan** [comment]
Can you make %{_datadir}/containers/systemd/qm.container
Config(noreplace)

**Comment by lsm5** [comment]
> Can you make %{_datadir}/containers/systemd/qm.container Config(noreplace)

sure thing

**Comment by lsm5** [comment]
@rhatdan done

**Comment by rhatdan** [comment]
:+1:

**Pull request merged**
