### PR TITLE
rename hirte to bluechi

### PR DESCRIPTION
**Pull request by dougsland**
Hirte project has being renamed to BlueChi.

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

### CODE REVIEW

**Comment by dougsland** [comment]
As expected the error is: "mperina/bluechi-snapshot centos-stream-9": while running runtime: exit status 1":

```
Please do not file bug reports about these packages in Fedora
        Bugzilla. In case of problems, contact the owner of this repository.
        Error: It wasn't possible to enable this project.
        Project mperina/bluechi-snapshot does not exist.
        Error: building at STEP "RUN dnf -y copr enable mperina/bluechi-snapshot centos-stream-9": while running runtime: exit status 1
        Error: repository name must have at least one component
```

@mwperina should we use hirte in these locations ? Or are we addressing soon the packaging repo renaming?

**Comment by mwperina** [comment]
COPR was not renamed, it's still available at https://copr.fedorainfracloud.org/coprs/mperina/hirte-snapshot/

I'm investigating the switch packit instead of this COPR repo: https://github.com/containers/bluechi/issues/452

**Comment by lsm5** [comment]
might be a good time to create the new copr under auto org to host both qm and bluechi

**Comment by rhatdan** [comment]
LGTM

**Comment by dougsland** [comment]
> might be a good time to create the new copr under auto org to host both qm and bluechi

+1

**Pull request merged**
