### PR TITLE
setup: add vim

### PR DESCRIPTION
**Pull request by dougsland**
add vim editor to the qm container

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by pypingou** [comment]
hm, I'm not sure we really want this. I doubt we want vim in cars and we can edit files from outside the qm partition if needed (`vim /usr/lib/qm/root/...`).
I agree that the CentOS Automotive SIG images aren't built using this script directly and are thus not affected by this change but I believe we still want to keep this script and the osbuild recipe as close as possible from each other.

**Comment by rhatdan** [comment]
Perhaps we should have a separate PR for setup tests from those which we will ship.  I agree we probably want to limit the potential attack surface within the QM.

**Comment by dougsland** [comment]
done: https://github.com/containers/qm/pull/274

**Comment by pypingou** [comment]
On Mon, Nov 06, 2023 at 06:47:54AM -0800, Douglas Landgraf wrote:
> done: https://github.com/containers/qm/pull/274

Thanks!

**Pull request merged**
