### PR TITLE
e2e: add gh tool

### PR DESCRIPTION
**Pull request by dougsland**
GitHub tool helps to bring patch easy for the test scenarios.

### CODE REVIEW

**Comment by dougsland** [comment]
the error not related to the patch. See: https://github.com/containers/qm/pull/94

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
> GitHub tool helps to bring patch easy for the test scenarios.

sorry, could you please explain this further? Maybe add a test case for this? Not opposed to this, but just curious why it's needed.

**Comment by dougsland** [comment]
> > GitHub tool helps to bring patch easy for the test scenarios.
> 
> sorry, could you please explain this further? Maybe add a test case for this? Not opposed to this, but just
> curious why it's needed.

Sure, I use the e2e tool locally as well. I have being testing hirte with patches from different developers and it's pretty quick to copy the command line from the `< > Code` button in Github to bring the PR to the environment and test. Example: `gh pr checkout PR_NUMBER`.  If this is bad, feel free to drop the PR. Just trying to make an auto environment for development and testing via qm e2e tool.

**Comment by lsm5** [comment]
> > > GitHub tool helps to bring patch easy for the test scenarios.
> > 
> > 
> > sorry, could you please explain this further? Maybe add a test case for this? Not opposed to this, but just
> > curious why it's needed.
> 
> Sure, I use the e2e tool locally as well. I have being testing hirte with patches from different developers and it's pretty quick to copy the command line from the `< > Code` button in Github to bring the PR to the environment and test. Example: `gh pr checkout PR_NUMBER`. If this is bad, feel free to drop the PR. Just trying to make an auto environment for development and testing via qm e2e tool.

Yes, I use `gh pr ..` too, but maybe we should let the user handle this themselves than pull in a dependency? If it's not really needed by CI itself, then maybe we can have this as an addon somewhere, maybe a couple of sed lines to update the Containerfile.template via a script in `contrib/` directory the human could run.

**Comment by dougsland** [comment]
> > > > GitHub tool helps to bring patch easy for the test scenarios.
> > > 
> > > 
> > > sorry, could you please explain this further? Maybe add a test case for this? Not opposed to this, but just
> > > curious why it's needed.
> > 
> > 
> > Sure, I use the e2e tool locally as well. I have being testing hirte with patches from different developers and it's pretty quick to copy the command line from the `< > Code` button in Github to bring the PR to the environment and test. Example: `gh pr checkout PR_NUMBER`. If this is bad, feel free to drop the PR. Just trying to make an auto environment for development and testing via qm e2e tool.
> 
> Yes, I use `gh pr ..` too, but maybe we should let the user handle this themselves than pull in a dependency?
> If it's not really needed by CI itself, then maybe we can have this as an addon somewhere, maybe a couple of
> sed lines to update the Containerfile.template via a script in `contrib/` directory the human could run.

I don't think it will change anything in CI but OK, completely understand.  I will handle that myself.

**Pull request closed without merging**
