### PR TITLE
github-actions: add test to build dropin targets

### PR DESCRIPTION
**Pull request by dougsland**
Just test if make dropin targets works

### CODE REVIEW

**Comment by dougsland** [comment]
I am sure soon we will do better validation than that but for now, is good to have something to guarantee we don't break the subpackages.

**Comment by Yarboa** [comment]
> I am sure soon we will do better validation than that but for now, is good to have something to guarantee we don't break the subpackages.

Please explain what is the goal of this PR

**Comment by dougsland** [comment]
> > I am sure soon we will do better validation than that but for now, is good to have something to guarantee we don't break the subpackages.
> 
> Please explain what is the goal of this PR

Create a github actions to execute a loop to all existing subpackages a

> > I am sure soon we will do better validation than that but for now, is good to have something to guarantee we don't break the subpackages.
> 
> Please explain what is the goal of this PR

Create a github actions that execute `make qm_dropin_<NAME_HERE>`. Please note `<NAME_HERE>` is dynamic the number of subpackages can increase or decrease with time.

**Comment by dougsland** [comment]
I should be back here soon, just finishing some work in the subpackage of Wayland. If anyone would like to continue this work, feel free.

**Comment by dougsland** [comment]
Resolves: https://github.com/containers/qm/issues/628

**Pull request merged**
