### PR TITLE
create a test case for setenforce 0 - create polarion TC

### PR DESCRIPTION
**Pull request by nsednev**
Set test automation-id

### CODE REVIEW

**Comment by nsednev** [comment]
In the original selinux test there was a missing Polarion ID in the main.fmf.
I've created the Polarion TC https://polarion.engineering.redhat.com/polarion/#/project/RHIVOS/workitem?id=RHIVOS-6337 ,which has the id: 0ebfdd87-65ee-4ee9-a3d7-24acaa01ce43.

**Review by Yarboa — COMMENTED** [review]
Please fix this one 
https://github.com/containers/qm/pull/496/checks?check_run_id=28045613402

I also edit the description, do not paste non upstream information
There are gate tests, please review the status of the tests

**Comment by Yarboa** [comment]
> In the original selinux test there was a missing Polarion ID in the main.fmf. I've created the Polarion TC https://polarion.engineering.redhat.com/polarion/#/project/RHIVOS/workitem?id=RHIVOS-6337 ,which has the id: 0ebfdd87-65ee-4ee9-a3d7-24acaa01ce43.

Please do not expose such data, please delete

**Comment by Yarboa** [comment]
> In the original selinux test there was a missing Polarion ID in the main.fmf. I've created the Polarion TC https://polarion.engineering.redhat.com/polarion/#/project/RHIVOS/workitem?id=RHIVOS-6337 ,which has the id: 0ebfdd87-65ee-4ee9-a3d7-24acaa01ce43.

Please delete this data, it is not relevant to public repo

**Review by Yarboa — APPROVED** [review]
LGTM

**Pull request merged**
