### PR TITLE
demo/e2e: add dashboard-tui

### PR DESCRIPTION
**Pull request by dougsland**
Initial dashboard-tui tool, requires tests/e2e/run-test-e2e to setup the environment. After that, just run the tool.

### CODE REVIEW

**Comment by dougsland** [comment]
@rhatdan @lsm5 @ygalblum PTAL. It's easier to review looking the HTML and video generated via README.md here: https://github.com/dougsland/qm/tree/main/tests/e2e/dashboard-tui

**Comment by pypingou** [comment]
Can you drop RHIVOS (and its version) from the TUI? RHIVOS hasn't been released yet and thus doesn't exist yet :)
(and I don't know what it's versioning schema will be)

**Comment by lsm5** [comment]
LGTM RE: demo, but I'll defer to others for final approval.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
