### PR TITLE
e2e: adjust the path for controller.conf

### PR DESCRIPTION
**Pull request by dougsland**
Currently, e2e is failing with timeout as the AllowedNames is not set correctly.

### CODE REVIEW

**Comment by dougsland** [comment]
@rhatdan @Yarboa PTAL.

**Comment by dougsland** [comment]
CI error will be fixed as soon the patch is merged.

**Review by Yarboa — COMMENTED** [review]
~@dougsland ci is passing, because of the previous fix
It will fail with it, and actually is failing now~

~I assume it is a bug in BlueChi~

> ~man bluechi-controller.conf | grep -A 4 FILE
> FILES
>        Distributions provide the /usr/share/bluechi/config/controller.conf  file  which  de‐
>        fines   bluechi   configuration  defaults.  Administrators  can  copy  this  file  to
>        /etc/bluechi/controller.conf and specify their own configuration.~
> 

 ~/etc/bluechi/controller.conf  is not read by the controller
 CI was failing since, the agents were not recognized by bluechi-controller~

**Review by mwperina — APPROVED** [review]
LGTM

**Review by Yarboa — CHANGES_REQUESTED** [review]
Do not forget to change the copy also
Gate tests are failing since it is not fully set
Please change this also
https://github.com/containers/qm/pull/255/files#diff-c60a4ee82a0781e7951ef4194038877d2a9f275dbc32fa70b85947428c31310eR148

And this will cause another failure for updating qm node name, let me check

**Comment by dougsland** [comment]
> Do not forget to change the copy also Gate tests are failing since it is not fully set Please change this also https://github.com/containers/qm/pull/255/files#diff-c60a4ee82a0781e7951ef4194038877d2a9f275dbc32fa70b85947428c31310eR148
> 
> And this will cause another failure for updating qm node name, let me check

Just checked, the agent is using the path /etc/bluechi/agent.conf.d/agent.conf

```
   # Enable bluechi-agent
        echo 'RUN cp /usr/share/bluechi-agent/config/*.conf /etc/bluechi/agent.conf.d/' >> ContainerFile.node"${nodeID}"
        echo 'RUN sed -i -e "s/^#NodeName=/NodeName='"node${nodeID}/"\" \
                '-e "s/^#ManagerHost=/ManagerHost='"${IP_CONTROL_MACHINE}/"\" \
                ' /etc/bluechi/agent.conf.d/agent.conf' >> ContainerFile.node"${nodeID}"
        echo "RUN systemctl enable bluechi-agent &> /dev/null" >> ContainerFile.node"${nodeID}"
```

**Pull request merged**
