### PR TITLE
Handle RHEL missing vsomeip packages

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Review by Yarboa — COMMENTED** [review]
I am not following 
So, do you plan to remove the dependency of vsomeip3_selinux from build?

**Comment by mwperina** [comment]
We need to bump version to 0.6.2 and then this fix might be built successfully: https://github.com/containers/qm/blob/main/VERSION

**Review by Yarboa — APPROVED** [review]
LGTM

**Comment by dougsland** [comment]
waiting CI/CD

**Review by dougsland — APPROVED** [review]

**Pull request merged**
