### PR TITLE
ffi: memory - increase duration to 50m

### PR DESCRIPTION
**Pull request by dougsland**
avoid timeout

### CODE REVIEW

**Comment by Yarboa** [comment]
I think the tests should be fixed, 
We need to trigger exit status faster, no to increase duration to 50 minutes.
WDYT?

**Comment by dougsland** [comment]
> I think the tests should be fixed, We need to trigger exit status faster, no to increase duration to 50 minutes. WDYT?
> 
> I would consider reducing autosd/ffi-tools image to slimmer version, to reduce image download time WDYT?

agreed.  I am testing, I was not convinced the 20m was the root cause and found other two problems.

```
Error: OCI runtime error: crun: the requested cgroup controller `pids` is not available
[ INFO  ] PASS: qm.container oom_score_adj value == 500
./test.sh: line 39: [: cat: /proc/0/oom_score_adj: No such file or directory: integer expression expected
[ INFO  ] FAIL: qm containers oom_score_adj != 750. Current value is cat: /proc/0/oom_score_adj: No such file or directory
```

**Comment by Yarboa** [comment]
There is an issue with automation
see that https://quay.io/organization/centos-sig-automotive

quay.ioquay.io
[Quay](https://quay.io/organization/centos-sig-automotive)
Quay is the best place to build, store, and distribute your containers. Public repositories are always free.
[3:40](https://redhat-internal.slack.com/archives/D057LJCLLAJ/p1724719236636919)
45 G

Need to clean

**Comment by Yarboa** [comment]
Closing #508 solved it with reduction of ffi-tools container

**Pull request closed without merging**
