### PR TITLE
make: add validation for rhel9 or lower

### PR DESCRIPTION
**Pull request by dougsland**

### CODE REVIEW

**Comment by rhatdan** [comment]
@lsm5 Can't we make this cleaner with RPM macros?

**Comment by rhatdan** [comment]
Ok so this is not in a rpm spec.  I still want to know why the original check is not working?

Can we just check for the existence of `/sys/fs/selinux/class/user_namespace`

**Comment by lsm5** [comment]
> Ok so this is not in a rpm spec. I still want to know why the original check is not working?
> 
> Can we just check for the existence of `/sys/fs/selinux/class/user_namespace`

@dougsland if the spec file patch was merged, do we still need this? Would people building directly from Makefile be affected without this patch?

**Comment by dougsland** [comment]
> > Ok so this is not in a rpm spec. I still want to know why the original check is not working?
> > Can we just check for the existence of `/sys/fs/selinux/class/user_namespace`
> 
> @dougsland if the spec file patch was merged, do we still need this? Would people building directly from
> Makefile be affected without this patch?

I think so. Even that we are a rpm shop only, it's always good to make the project friendly to others distros that would like to use it.

**Comment by dougsland** [comment]
> Ok so this is not in a rpm spec. I still want to know why the original check is not working?
> 
> Can we just check for the existence of `/sys/fs/selinux/class/user_namespace`

In the Github Actions Virtual Machine it exists in my local podman CentOS Stream 9 nop.

**Comment by lsm5** [comment]
@dougsland ack, sgtm. But to make sure this works, can you also get rid of all the conditionals in rpm/qm.spec to handle rhel 9 ? The centos 9 copr builds should pass with those removed.

**Comment by rhatdan** [comment]
LGTM
@lsm5 PTAL

**Comment by lsm5** [comment]
@dougsland squash commits and we're good to merge.

**Pull request merged**
