### PR TITLE
Gate run requires epel targets

### LINKED ISSUE #299: Enable packit rpm build and test with epel repo dependency
Based on this PR #244 
There is BuildRequires: vsomeip3-selinux >= 3.3.8
Which exist in epel repos

Need to map centos-stream+epel-next-9 -> in test part to centos-stream-9

Opened new PR for tests
#298

### PR DESCRIPTION
**Pull request by Yarboa**
With introduction of vsomeip-selinux
as build dependency c9s target build is failing

resolve #299

### CODE REVIEW

**Comment by lsm5** [comment]
not sure why you're getting the copr enablement errors in testing farm, is it that you're specifying `centos-stream-9` as an argument while enabling copr? In my experience, all rhel and rhel-related envs pick `epel-` as the default target when you do a `dnf copr enable`.

**Comment by Yarboa** [comment]
Closing, https://github.com/containers/qm/pull/320 replace and try to suggest c9s gating

**Comment by Yarboa** [comment]
Closing, https://github.com/containers/qm/pull/320 replace and try to suggest c9s gating

**Pull request closed without merging**
