### PR TITLE
docs: Adding docs/quadlet-examples dir

### PR DESCRIPTION
**Pull request by dougsland**
Initial commit provided by Dan Walsh running android container on top of kvm + wayland.

### CODE REVIEW

**Comment by dougsland** [comment]
@sandrobonazzola if Dan accepts this doc, could you please also add your tutorial here ?

**Comment by rhatdan** [comment]
LGTM

**Comment by sandrobonazzola** [comment]
> @sandrobonazzola if Dan accepts this doc, could you please also add your tutorial here ?

Sure

**Pull request merged**
