### PR TITLE
Pr_77

### LINKED ISSUE #72: e2e tool: transform ContainerFile.control to ContainerFile.template
Let's rename ContainerFile.control to ContainerFile.template and during the start of the program we execute: `cp ContainerFile.template` to `ContainerFile.control`

https://github.com/containers/qm/blob/main/tests/e2e/ContainerFile.control

Also, we need to add ContainerFile.control into the `gitignore`
https://github.com/containers/qm/blob/main/tests/e2e/.gitignore

### PR DESCRIPTION
**Pull request by Yarboa**
Resolve #72 

During the push to this PR PR has closed, can not reopen
Proposing new PR instead of this 

https://github.com/containers/qm/pull/77

### CODE REVIEW

**Comment by rhatdan** [comment]
Please fix the DCO

**Comment by dougsland** [comment]
Thanks @adityakode @Yarboa. As Dan mentioned, fix DCO and we should be fine.

**Review by Yarboa — COMMENTED** [review]
e2e i failing on this, Please fix
Error: stat /var/ARTIFACTS/work-tier-0zbew6jc9/tests/e2e/tier-0/tree/tests/e2e/ContainerFile.template: no such file or directory

**Comment by lsm5** [comment]
LGTM pending testing-farm task and commit squashing.

**Review by dougsland — CHANGES_REQUESTED** [review]
looks like we need more changes, @Yarboa please take a look.

**Review by Yarboa — COMMENTED** [review]
Test is failing on first container, since it takes it more then 5 seconds
Have to add 
https://github.com/containers/qm/blob/main/tests/e2e/lib/systemd#L117

Here a check about the output or wait time our

**Comment by dougsland** [comment]
LGTM
lets' fly!

**Review by dougsland — APPROVED** [review]

**Pull request merged**
