### PR TITLE
tests/ffi: add test checking /sys is read-only

### PR DESCRIPTION
**Pull request by aesteve-rh**
Test to ensure that /sys is read-only inside the
QM container.

### CODE REVIEW

**Comment by Yarboa** [comment]
It seems that test is failing 
https://artifacts.dev.testing-farm.io/d64d0683-89c7-4295-9cdf-121b7c21b981/work-ffi1ofe9kw2/plans/e2e/ffi/execute/data/guest/default-0/tests/ffi/sys_read_only-20/output.txt

And fedora failure is not related to PR, see #666

**Review by Yarboa — COMMENTED** [review]
LGTM,
@pengshanyu can you please review?

**Comment by aesteve-rh** [comment]
> It seems that test is failing
https://artifacts.dev.testing-farm.io/d64d0683-89c7-4295-9cdf-121b7c21b981/work-ffi1ofe9kw2/plans/e2e/ffi/execute/data/guest/default-0/tests/ffi/sys_read_only-20/output.txt

Interesting, folder is there with right permissions. It seems that the `podman exec` is not doing the right thing. I'd say I tested yesterday, but I'll try again. Maybe it needs ` -t` parameter, or `/bin/sh -c 'test ..'`, or both.

**Comment by aesteve-rh** [comment]
Looks like the error is gone, the failing test is unrelated?

**Review by Yarboa — APPROVED** [review]
LGTM

**Review by dougsland — APPROVED** [review]
LGTM, test failure not related.  It seems related to podman issue Yariv and Giuseppe are working.

**Comment by dougsland** [comment]
> @pengshanyu can you please review?

+1

**Comment by pengshanyu** [comment]
LGTM.

**Pull request merged**
